
# Machine executor, set the machine key to true in .circleci/config.yml:
version: 2.1
orbs:
  secrethub: secrethub/cli@1.0.0
jobs:
  mvn_deploy:
    machine:
      resource_class: medium
      image: 'ubuntu-1604:201903-01'    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      # docker_layer_caching: true    # default - false # requires a Circle CI plan that includes [Docker layer caching feature]
    environment:
      JFROG_BUILD_NUMBER: 1524548
      DESIRED_MAVEN_VERSION: 3.6.3
      GUARDIAN_GIT_URI: "https://github.com/gravitee-lab/gravitee-gateway"
      GUARDIAN_VERSION: 3.1.1
    steps:
      - checkout
      - secrethub/install
      - run:
          name: "Maven clean install the maven project"
          command: |
                    export MVN_DOCKER_IMAGE="maven:${DESIRED_MAVEN_VERSION}-openjdk-16 "
                    export MAVEN_COMMAND="mvn -T 4 clean install -DskipTests"
                    echo "MAVEN_COMMAND=[${MAVEN_COMMAND}]"
                    docker run -it --rm -v "$PWD/gio-maven-project":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -w /usr/src/mymaven ${MVN_DOCKER_IMAGE} ${MAVEN_COMMAND}

      - run: # maven deploy
          name: "Maven Deploy the Gravitee Component to Central Maven Repo : JFrog / Clevercloud"
          command: |
                    echo "# --------------------------------------------------------"
                    echo "Copy settings.xml into [$PWD/gio-maven-project/] folder"
                    echo "# --------------------------------------------------------"
                    cp $PWD/dry-run-conf/settings.xml $PWD/gio-maven-project/
                    echo "# --------------------------------------------------------"
                    ls -allh $PWD/gio-maven-project/settings.xml
                    cat $PWD/gio-maven-project/settings.xml
                    echo "# --------------------------------------------------------"
                    echo "Run Maven Deploy using JFrog Maven Plugin"
                    echo "# --------------------------------------------------------"
                    export MVN_DOCKER_IMAGE="maven:${DESIRED_MAVEN_VERSION}-openjdk-16"
                    #
                    # see https://github.com/jfrog/project-examples/tree/master/artifactory-maven-plugin-example
                    export SECRETHUB_ORG="gravitee-lab"
                    export SECRETHUB_REPO="cicd"
                    export ARTIFACTORY_BOT_USER_NAME=$(secrethub read "${SECRETHUB_ORG}/${SECRETHUB_REPO}/graviteebot/infra/maven/dry-run/artifactory/user-name")
                    export ARTIFACTORY_BOT_USER_PWD=$(secrethub read "${SECRETHUB_ORG}/${SECRETHUB_REPO}/graviteebot/infra/maven/dry-run/artifactory/user-pwd")
                    export JFROG_BUILD_NUMBER=${CIRCLE_SHA1}
                    echo "JFROG_USERNAME=[${JFROG_USERNAME}]"
                    # echo "JFROG_SECRET=[${JFROG_SECRET}]"
                    export MAVEN_COMMAND="mvn -T 4 deploy -Dgio.username=${ARTIFACTORY_BOT_USER_NAME} -Dgio.password=${ARTIFACTORY_BOT_USER_PWD} -Dbuildnumber=${JFROG_BUILD_NUMBER} -DskipTests"
                    echo "MAVEN_COMMAND=[${MAVEN_COMMAND}]"
                    docker run --name mvndeploy -it --rm -v "$PWD/gio-maven-project":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -w /usr/src/mymaven ${MVN_DOCKER_IMAGE} ${MAVEN_COMMAND}
workflows:
  version: 2.1
  maven_deploy:
    # triggers:
      # - schedule:
          # Every sunday at midnight UTC
          # cron: "0 0 * * *"
          # not supported by Circle CI
          # cron: "*/5 * * * *"
          # cron: '* * * * *'
          # Every hour UTC
          # cron: "0 * * * *"
          # filters:
            # branches:
              # only:
                # - master
    jobs:
      - mvn_deploy:
          context: cicd-orchestrator
          # filters:
            # tags:
              # only: /^stable-latest/
            # branches:
              # ignore: /.*/
