
# Machine executor, set the machine key to true in .circleci/config.yml:
version: 2.1

orbs:
  secrethub: secrethub/cli@1.0.0
  gravitee: gravitee-io/gravitee@dev:1.0.2

jobs:
  mvn_deploy_gravitee_parent:
    machine:
      resource_class: medium
      image: 'ubuntu-1604:201903-01'    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      # docker_layer_caching: true    # default - false # requires a Circle CI plan that includes [Docker layer caching feature]
    environment:
      GIO_BUILD_NUMBER: 1524548
      DESIRED_MAVEN_VERSION: 3.6.3
      GUARDIAN_GIT_URI: "https://github.com/gravitee-lab/gravitee-gateway"
      GUARDIAN_VERSION: 3.1.1
    steps:
      # I do not checkout the source code of
      # the [clever-cloud-artifactory-deployment-prototype] git repo, but the
      # https://github.com/gravitee-lab/gravitee-parent repo
      # -
      # - checkout
      - run:
          name: "Redefine Gravitee Parent POM in clevercloud referential"
          command: |
                    git clone https://github.com/gravitee-lab/gravitee-parent ./
                    git checkout 17.x
      - secrethub/install
      - gravitee/mvn_release:
          dry_run: true
          # maven_version: 3.6.3
          dry_run_mvn_profile_id: ${DRY_RUN_MVN_PROFILE_ID}
          secrethub_org: gravitee-lab
          secrethub_repo: cicd

  mvn_deploy_gravitee_component:
    machine:
      resource_class: medium
      image: 'ubuntu-1604:201903-01'    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      # docker_layer_caching: true    # default - false # requires a Circle CI plan that includes [Docker layer caching feature]
    steps:
      # I do not checkout the source code of
      # the [clever-cloud-artifactory-deployment-prototype] git repo, but the
      # https://github.com/gravitee-lab/gravitee-common repo
      # - checkout
      - run:
          name: "Redefine Gravitee Parent POM in clevercloud referential"
          command: |
                    git clone https://github.com/gravitee-lab/gravitee-common ./
                    git checkout 1.18.x
      - secrethub/install
      - gravitee/mvn_release:
          dry_run: true
          # maven_version: 3.6.3
          dry_run_mvn_profile_id: ${DRY_RUN_MVN_PROFILE_ID}
          secrethub_org: gravitee-lab
          secrethub_repo: cicd

workflows:
  version: 2.1
  maven_deploy:
    # triggers:
      # - schedule:
          # Every sunday at midnight UTC
          # cron: "0 0 * * *"
          # not supported by Circle CI
          # cron: "*/5 * * * *"
          # cron: '* * * * *'
          # Every hour UTC
          # cron: "0 * * * *"
          # filters:
            # branches:
              # only:
                # - master
    jobs:
      - mvn_deploy_gravitee_parent:
          context: cicd-orchestrator
          # filters:
            # tags:
              # only: /^stable-latest/
            # branches:
              # ignore: /.*/
      - mvn_deploy_gravitee_component:
          context: cicd-orchestrator
          # filters:
            # tags:
              # only: /^stable-latest/
            # branches:
              # ignore: /.*/
          requires:
            - mvn_deploy_gravitee_parent
