
# Machine executor, set the machine key to true in .circleci/config.yml:
version: 2.1

parameters:
  gio_action:
    type: enum
    enum: [release, pr_build]
    default: pr_build
  dry_run:
    type: boolean
    default: true
    description: "Run in dry run mode ?"
  dry_run_mvn_profile_id:
    type: string
    # default: "gravitee-dry-run"
    default: "gravitee-release"
    description: "Maven ID of the Maven profile to use for a dry run ?"
  secrethub_org:
    type: string
    default: "gravitee-lab"
    description: "SecretHub Org to use to fetch secrets ?"
  secrethub_repo:
    type: string
    default: "cicd"
    description: "SecretHub Repo to use to fetch secrets ?"

orbs:
  secrethub: secrethub/cli@1.0.0
  gravitee: gravitee-io/gravitee@dev:1.0.2

jobs:
  mvn_deploy_gravitee_parent:
    machine:
      resource_class: medium
      image: 'ubuntu-1604:201903-01'    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
    steps:
      # I do not checkout the source code of
      # the [clever-cloud-artifactory-deployment-prototype] git repo, but the
      # https://github.com/gravitee-lab/gravitee-parent repo
      # -
      # - checkout
      - run:
          name: "Redefine Gravitee Parent POM in clevercloud referential"
          command: |
                    git clone https://github.com/gravitee-lab/gravitee-parent ./
                    git checkout 17.x
      - run:
          name: "Checking context variables"
          command: |
                    echo "DRY_RUN=[$DRY_RUN]"
                    echo "DRY_RUN_MVN_PROFILE_ID=[${DRY_RUN_MVN_PROFILE_ID}]"
                    echo "SECRETHUB_ORG=[${SECRETHUB_ORG}]"
                    echo "SECRETHUB_REPO=[${SECRETHUB_REPO}]"
      - run:
          name: "Creating GPG Key tests"
          command: |
                    # https://www.gnupg.org/documentation/manuals/gnupg-devel/Unattended-GPG-key-generation.html
                    export GNUPGHOME="$(mktemp -d)"
                    cat >gravitee-lab-cicd-bot <<EOF
                         %echo Generating a basic OpenPGP key
                         Key-Type: DSA
                         Key-Length: 1024
                         Subkey-Type: ELG-E
                         Subkey-Length: 1024
                         Name-Real: Joe Tester
                         Name-Comment: with stupid passphrase
                         Name-Email: joe@foo.bar
                         Expire-Date: 0
                         Passphrase: abc
                         # Do a commit here, so that we can later print "done" :-)
                         %commit
                         %echo done
                    EOF
                    gpg --batch --generate-key gravitee-lab-cicd-bot
                    echo "GNUPGHOME=[${GNUPGHOME}]"
                    ls -allh ${GNUPGHOME}
      - secrethub/install
      - gravitee/mvn_release:
          dry_run: << pipeline.parameters.dry_run >>
          # maven_version: 3.6.3
          dry_run_mvn_profile_id: << pipeline.parameters.dry_run_mvn_profile_id >>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>

  mvn_deploy_gravitee_component:
    machine:
      resource_class: medium
      image: 'ubuntu-1604:201903-01'    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
    steps:
      # I do not checkout the source code of
      # the [clever-cloud-artifactory-deployment-prototype] git repo, but the
      # https://github.com/gravitee-lab/gravitee-common repo
      # - checkout
      - run:
          name: "Redefine Gravitee Parent POM in clevercloud referential"
          command: |
                    git clone https://github.com/gravitee-lab/gravitee-common ./
                    git checkout 1.18.x
      - run:
          name: "Checking context variables"
          command: |
                    echo "DRY_RUN=[$DRY_RUN]"
                    echo "DRY_RUN_MVN_PROFILE_ID=[${DRY_RUN_MVN_PROFILE_ID}]"
                    echo "SECRETHUB_ORG=[${SECRETHUB_ORG}]"
                    echo "SECRETHUB_REPO=[${SECRETHUB_REPO}]"
      - secrethub/install
      - gravitee/mvn_release:
          dry_run: << pipeline.parameters.dry_run >>
          # maven_version: 3.6.3
          dry_run_mvn_profile_id: << pipeline.parameters.dry_run_mvn_profile_id >>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>

workflows:
  version: 2.1
  maven_deploy:
    jobs:
      - mvn_deploy_gravitee_parent:
          context: cicd-orchestrator
          # filters:
            # tags:
              # only: /^stable-latest/
            # branches:
              # ignore: /.*/
      - mvn_deploy_gravitee_component:
          context: cicd-orchestrator
          # filters:
            # tags:
              # only: /^stable-latest/
            # branches:
              # ignore: /.*/
          requires:
            - mvn_deploy_gravitee_parent
